services:
  - type: web
    name: jarvis-backend
    env: docker
    root: .
    repo: https://github.com/ScriptsHub07/app_backend.git
    branch: main
    dockerfilePath: Dockerfile
    plan: starter

databases:
  - name: jarvis-db
    plan: free
    postgresVersion: "18"
